### ISSUE TITLE
Players can run campaign macros on tokens they don't own

### ISSUE THREAD

**Issue by mbbhudgins** [virenerus/tabletoptool#22]
Host a server with strict Token ownership and campaign macros.
A player connecting to the server can run campaign macros on tokens they don't own or have permissions to.

**Comment by virenerus** [comment]
Mhh. This is more or less by design at the moment. A secure macro engine is not really possible without severly restricting the capabilities of the engine. I thus decided at the beginning of this project that T³ is a tool for a social group, not a uncheatable game. Players could also fake dice rolls by simply writing the expected output of a roll to the chat or they could simply access the none secured methods outside of the specified API directly. It's not possible to make T³ secure against cheaters. I think that is something that every group has to solve themselves.

What do you think?

**Comment by mbbhudgins** [comment]
I agree that it's not of the most importance and that it is not be design secure, but does mean that a given macro has to check ownership of each returned token in a selected group. This also can prevent accidents which can muddle the flow of game play. I think it's something to consider.

Though, perhaps there is a compromise? similar to the getSelectedToken, have a getSelectedOwned? Token macro writers can then know the list they're returned only is owned by the person issuing the macro statement. Or if they want to select all tokens regardless of permissions, they can use the current syntax? Seems a simple API call to add. Thoughts?
